services:
  app:
    build: .
    volumes:
      - admin-laufane-data:/var/www/html
    container_name: ${PREFIX}-app
    restart: unless-stopped
    networks:
      - admin-laufane-network

  webserver:
    image: nginx:1.24.0-alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - admin-laufane-data:/var/www/html:ro
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: ${PREFIX}-nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - admin-laufane-network
      

volumes:
  admin-laufane-data:
  mysql-data:

networks:
  admin-laufane-network:
    driver: bridge
